### ISSUE TITLE
Toggle main window with same key

### ISSUE THREAD

**Issue by mockroot** [Shatur95/crow-translate#18]
It would be great if we can toggle main window with same key instead of closing with Esc.
Like this: If window active, same key closes; else, activate main window.

**Comment by Shatur95** [comment]
Sorry, but I think that this is not consistent, because the window can be showed in two ways. Using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd> and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> (by default). It seems to me that <kbd>Ctrl</kbd> + <kbd>Q</kbd> is enough and more logical to close the window.

**Comment by mockroot** [comment]
OK. I can live with it :) Thanks for your work.

**Comment by mockroot** [comment]
Maybe comnand line option, if it's not hard to do?

**Comment by Shatur95** [comment]
> Maybe command line option, if it's not hard to do?

It will be even more weird :)

**Comment by mockroot** [comment]
thank you for your time, I love your program.

**Comment by Shatur95** [comment]
Nice to read :)
